[package]
name = "audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xshell = "0.2.2"
anyhow = "1.0.62"

[dependencies.clap]
version = "3.2.17"
features = ["derive"]
